### ISSUE TITLE
Declarative jobset not creating jobsets?

### ISSUE THREAD

**Issue by lukego** [NixOS/hydra#453] opened 2017-03-28 20:53 UTC
Howdy!

I am experimenting with declarative jobsets for the first time. Exciting feature! I have tried to follow the instructions but it is not entirely working:

- Created a [repo](https://github.com/raptorjit/hydra-jobsets) containing `spec.json` and `default.nix`.
- Configured the declarative jobset, saw the `.jobsets` appear, successfully evaluated.
- But: The jobset defined in the file ("hotcounts") did not appear...?

So I am wondering if I missed a step? (I'm also wondering if the declarative jobsets will co-exist with my manually created ones, or if those are at risk of being deleted since they don't exist in the declarative spec?)

also: any tips on migrating existing jobs to declarative mode? (copy & paste from the Configuration page?)

Thanks for the great feature!

**Comment by lukego** [comment] 2017-03-28 20:54
Oh here is the link to the relevant project: https://hydra.snabb.co/project/raptorjit.

Note the "hotcount" jobset is manually created and it is "hotcounts" (plural) that is defined declaratively.

**Comment by globin** [comment] 2017-03-30 19:40
Duplicate of #443

**Closed** 2017-04-01 11:51 UTC
