### ISSUE TITLE
hydra-server leaks memory

### ISSUE THREAD

**Issue by mornfall** [NixOS/hydra#120] opened 2013-09-21 12:03 UTC
# echo $(( $(cat .../hydra-server.service/memory.memsw.usage_in_bytes) / (1024 \* 1024)))
27117
# restart hydra-server
...
#  echo $(( $(cat .../hydra-server.service/memory.memsw.usage_in_bytes) / (1024 \* 1024)))
169

this is after a couple days of normal operation behind an nginx reverse proxy

**Comment by gilligan** [comment] 2020-05-11 14:50
since no such problems seem to currently exist for hydra.nixos.org and there is no way of reproducing anything about this i will close this issue.

**Closed by gilligan** 2020-05-11 14:50 UTC
