### ISSUE TITLE
Build logs being deleted immediately

### ISSUE THREAD

**Issue by rgmorris** [NixOS/hydra#456] opened 2017-03-31 23:04 UTC
Hi,

It seems that at the moment, hydra build logs are being deleted immediately after jobs finish.
Eg at time of writing http://hydra.nixos.org/build/51098328 finished 20 minutes ago,
but already the log is gone.
Normally there is a "log" link. The "log diff" button is still present, but leads to a 404.
This makes it hard to diagnose the reasons for build failures.

Thanks.

**Comment by domenkozar** [comment] 2017-04-01 09:20
@edolstra

**Comment by vcunat** [comment] 2017-04-01 15:00
I think it's been happening for at least a week now, and it really makes fixing problems harder (especially on platforms where you can't run the build yourself).

**Comment by dtzWill** [comment] 2017-04-03 23:08
Looking through recent history for other reasons, [this commit](https://github.com/NixOS/hydra/commit/150228d7dec499a763a8f76477aa35310771fd84#diff-925137e29294f8f78d6dce473551467fR158) looks like it might be the cause here.

If so, looks like maybe the problem is teaching hydra to link to the build logs that have been uploaded?

**Comment by edolstra** [comment] 2017-04-04 08:48
I'm working on it right now.

**Comment by vcunat** [comment] 2017-04-05 19:29
Fixed by fec895a6421, I guess?  It seems to work, for some logs at the very least.

**Comment by vcunat** [comment] 2017-04-05 19:32
I was interested in http://hydra.nixos.org/build/51148812, but apparently it dies before uploading any log.  That's consistent with the report that the error can't be reproduced locally...

**Comment by rgmorris** [comment] 2017-04-06 20:50
Looks like the logs are back now, thanks!
But the actual builds themselves still seem to be disappearing immediately, which is a problem with a failed build if you want to download the closure to inspect it locally.

**Comment by vcunat** [comment] 2017-04-10 14:36
Failed builds don't hold any closure in nix, as they're not valid nix store paths.

**Comment by rgmorris** [comment] 2017-04-10 19:08
I'm talking about the "Failed build produced output. Click here to inspect the output." button,
and the "Help" action that describes how to fetch a closure and import it locally.
See eg http://hydra.nixos.org/build/51419703 . Those links stop working as soon as the build ends ("Product /nix/store/... has disappeared"). They used to work in the past.

**Comment by vcunat** [comment] 2017-04-10 19:38
I see.

**Comment by edolstra** [comment] 2017-04-11 12:57
Yeah fixed in fec895a6421a99e76772dc284a01cafe1c39d310.

**Closed by edolstra** 2017-04-11 12:57 UTC
