### ISSUE TITLE
how to return a temporary failure from a builder?

### ISSUE THREAD

**Issue by jcumming** [NixOS/hydra#363] opened 2016-07-14 15:36 UTC
Is it possible to return a temporary failure from a builder? 
 * a magic exit code
 * perhaps a file $out/hydra-build-products/transient_failure

**Comment by copumpkin** [comment] 2016-07-14 15:41
This seems most relevant to fixed-output derivations, right? Or why would you want it on non-fixed ones?

**Comment by jcumming** [comment] 2016-07-14 18:41
I have a case where I need token that I can't reserve until I start. 

If I start the job and don't get the token, I want to use the exponential random backoff heuristic.

**Comment by copumpkin** [comment] 2016-07-14 18:44
Ah, so you have an impure builder? Or is this for something with a fixed output?

**Comment by jcumming** [comment] 2016-07-14 18:53
The license token doesn't affect the outputs of the build, but the build can't proceed without it. 

Previously, I've used sophisticated scheduling and reservation schemes to prevent resource collision, but random exponential backoff seems to work just as well.

**Comment by rickynils** [comment] 2016-07-20 11:15
I would also have use for a way to signal transient failures. I have some integration builds that make use of the `libvirtd` daemon on the build host to run tests inside VMs and containers. Sometimes these builds fail due to failures in libvirt (triggering bugs, OOM, timeouts due to many parallel VMs etc). It would be nice if Hydra could just schedule such builds for re-run instead of failing them.

**Comment by rickynils** [comment] 2016-07-20 11:17
Btw, this is probably a duplicate of #354

**Comment by domenkozar** [comment] 2016-07-25 11:46
Yes, closing so discussion can take place in one location.

**Closed by domenkozar** 2016-07-25 11:46 UTC
Labels: question
