### ISSUE TITLE
Jobset eval of `glibc231` breaks on `hydra.nixos.org`

### ISSUE THREAD

**Issue by Ma27** [NixOS/hydra#766] opened 2020-05-23 22:25 UTC
After rebasing the [`glibc231`](https://github.com/NixOS/nixpkgs/tree/glibc231)-branch onto latest `staging`, I tried to evaluate the [corresponding Hydra jobset](https://hydra.nixos.org/jobset/nixpkgs/glibc-231).

However, the [latest eval](https://hydra.nixos.org/jobset/nixpkgs/glibc-231#tabs-errors) broke with a DB error:

```
DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::Pg::st execute failed: ERROR:  insert or update on table "builds" violates foreign key constraint "fk3"
DETAIL:  Key (project, jobset, job)=(nixpkgs, glibc-231, xfce.xfce4_cpufreq_plugin.aarch64-linux) is not present in table "jobs". [for Statement "UPDATE builds SET iscurrent = ? WHERE ( id IN ( SELECT build.id FROM jobsetevalmembers me  JOIN builds build ON build.id = me.build WHERE ( me.eval = ? ) ) )" with ParamValues: 1='1', 2='1589095'] at /nix/store/zwhrmhwqkwwvg6454z320993g6947z0c-hydra-0.1.20200512.15a45f1/bin/.hydra-eval-jobset-wrapped line 750

```

**Comment by grahamc** [comment] 2020-05-24 01:25
I'm wondering if this is related 721c7649517ec1cd867371c1d1241d6a6781afc7

**Comment by grahamc** [comment] 2020-05-24 01:54
My friendly neighborhood perl monger says it isn't.

**Comment by FRidh** [comment] 2020-05-24 07:09
Duplicate of https://github.com/NixOS/nixpkgs/issues/88618.

**Comment by Ma27** [comment] 2020-05-24 08:50
> I'm wondering if this is related 721c764

Well, this only removes the retry behavior which used to be needed for the SQLite backend. And unless there's a weird timing issue I don't think that retried transactions should fix foreign-key violations, right?

**Comment by edolstra** [comment] 2020-05-27 13:21
Looks like our database was in a broken state where the `Jobs` table contained duplicates even though the constraints forbid that. So Postgres got very confused, making it unable to SELECT rows that definitely did exist, e.g.
```
hydra=# select * from jobs where jobset_id = 83 and name = 'nixpkgs.gnome3.gsettings_desktop_schemas.x86_64-linux';
 project |    jobset     |                         name                          | jobset_id
---------+---------------+-------------------------------------------------------+-----------
 nixos   | release-19.09 | nixpkgs.gnome3.gsettings_desktop_schemas.x86_64-linux |        83
(1 row)

hydra=# select * from jobs where project = 'nixos' and jobset = 'release-19.09' and jobset_id = 83 and name = 'nixpkgs.gnome3.gsettings_desktop_schemas.x86_64-linux';
 project | jobset | name | jobset_id
---------+--------+------+-----------
(0 rows)
```

The second query uses the `jobs_pkey` which appeared to have incorrect data.

FWIW here's how I fixed it:
```
# alter table builds drop constraint fk3;
# delete from jobs a using (SELECT MIN(ctid) as ctid, project, jobset_id, name
        FROM jobs 
        GROUP BY project, jobset_id, name HAVING COUNT(*) > 1
      ) b where a.project = b.project and a.jobset_id = b.jobset_id and a.name = b.name and a.ctid <> b.ctid;
# reindex index jobs_pkey;
# alter table builds ADD FOREIGN KEY (jobset_id) REFERENCES Jobsets(id) ON DELETE CASCADE;
```

**Closed by edolstra** 2020-05-27 13:21 UTC

**Comment by Ma27** [comment] 2020-05-27 14:00
Awesome, thanks!
