### ISSUE TITLE
Get rid of jobset alts

### ISSUE THREAD

**Issue by shlevy** [NixOS/hydra#279] opened 2016-03-12 13:32 UTC
They seem to complicate the code to basically no purpose nowadays (with `genAttrs` and nix jobset inputs especially).

**Comment by domenkozar** [comment] 2016-05-23 19:27
What are alts?

**Comment by shlevy** [comment] 2016-05-23 20:17
Exactly :grin: I think the idea is to reevaluate the same release.nix with multiple versions of an input, originally needed to support multiple systems? But now we can pass arbitrary nix expressions as inputs, so you can just pass them as a list.

**Comment by domenkozar** [comment] 2016-05-23 20:23
Where do you even specify alts? :D

**Comment by shlevy** [comment] 2016-05-23 20:33
Hmm, I'm not sure you even can anymore.

**Comment by domenkozar** [comment] 2016-05-23 20:33
Cool, let's do it :)

**Comment by edolstra** [comment] 2016-05-24 09:08
This is basically a dupe of #60.

**Comment by domenkozar** [comment] 2016-08-04 20:32
See #375

**Closed** 2018-01-19 17:33 UTC
