### ISSUE TITLE
Impossible to download any .deb file

### ISSUE THREAD

**Issue by 0tus** [NixOS/hydra#449] opened 2017-02-03 17:30 UTC
Hello,

On every .deb file that I try to download, I get the following:

```
404 Not Found

File /nix/store/[hash]-[name]/debs/[file-name].deb has disappeared.
```

So I'm not able to follow this WIKI article : https://nixos.org/wiki/Installing_Nix_on_Debian

Thanks

**Comment by globin** [comment] 2017-02-06 14:47
Duplicate of #321

**Closed** 2017-02-07 12:32 UTC
