### ISSUE TITLE
log buttons not correct if cached from a non-final build step

### ISSUE THREAD

**Issue by vcunat** [NixOS/hydra#462] opened 2017-04-10 14:40 UTC
It's possible it only happens for S3-stored logs after fec895a6421 (/cc #456). Example: http://hydra.nixos.org/build/51343495  The button leads to the log of the *final* step of the job, even if the build is actually cached from some earlier step.

**Comment by vcunat** [comment] 2017-04-10 14:43
Maybe it's related to the fact that the ["intended log location"](https://nix-cache.s3.amazonaws.com/log/vvb7gn91cg35s7v37y4aajqsbz502jdf-gnutls-3.5.10.drv) shows *access denied*.

**Comment by edolstra** [comment] 2017-04-11 10:46
The access denied is probably caused by a bug fixed in 8364f4ec7046a51d0a5179f52c7f2304b4c78bdd.

**Closed** 2017-04-11 12:26 UTC
